### PR TITLE
New York Times page

### PR DESCRIPTION
**Pull request by dannkkie**
Project completed together  with @PhiPhiPhi and request your  honest review

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @dannkkie  and @PhiPhiPhi :wave: 

Nice work so far. You guys are doing great, however, let's fix these issues listed below.

**Bottom Part**
* [x] It contains links to other articles with image previews on the leftmost side.
* [x] It contains links to more popular articles on the rightmost side.

Your clone has the said links to other articles but not complete. Also, there is supposed to be a `Most Popular` section to the right. Make sure you are looking at the [right page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

**Theirs**
review-nytimes-main


**Yours**
review-nytimes-clone


**Footer**
- [x] The footer has to be fixed. Refer to [the page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0) also.

- [x] Finally, let's properly setup stickler for this repo.


**Kindly submit another code review request after making those changes.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by dannkkie** [comment]
One problem we are having is each access to the page gives us different content so we cant tell what is needed. The most popular article and preview with images dont show up when we open the said page

**Comment by ebukaume** [comment]
> One problem we are having is each access to the page gives us different content so we cant tell what is needed. The most popular article and preview with images dont show up when we open the said page

Can I see screenshots? Are you sure you are not opening the home page?

**Comment by dannkkie** [comment]
@ebukaume this is the screenshot of the page

Screenshot from 2019-11-02 07-06-29

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi team :wave: 

You guys are doing great. I really love the hard work and perseverance, please keep it up. The clone now looks great.

However, **the footer is not fixed to the bottom like the header. Please make this happen so we can move forward.** _If the footer is not sticky on your side, please let us know, with a picture prove._

**Kindly fix that issue and submit another code review request**


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by dannkkie** [comment]
Below is the original nyt page it doesn't have a sticky footer like the header see image below
footer

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  🛑

### Hello team  🌟

**Nice job on this project, but we to implement all the required changes in order to move forward ⬇️** 

- Please make give the footer a fixed position.

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by dannkkie** [comment]
Please per the page we have access to the footer is not fixed which i have provided a pictorial evidence to that effect.

**Review by KaushikShivam — CHANGES_REQUESTED** [review]
# Status: Changes Required.

Hello guys! 👋 

Good work! I realize that you guys are having issues with the fixed footer. Unfortunately, that's one of the requirements. 

I tried getting in touch with you on slack but I guess you're unavailable at the moment. It's alright. :)

There could be a number of reasons why you're not seeing the footer. I checked it in 2 devices and it shows up. So, I went ahead and took a screenshot for you guys to reference to implement the footer.

You guys have a great pace. I'm sure it won't take you much time. 

 ### That's all, guys! 
**Make these changes and submit for a code review, again**
**If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**

Happy coding! 😄 
[Shivam Kaushik](https://github.com/KaushikShivam)
[Github](https://github.com/KaushikShivam) [Twitter](https://twitter.com/kShivamDev) [Linkedin](https://www.linkedin.com/in/shivam-kaushik-bb8162102/)

Screen Shot 2019-11-05 at 4 17 57 PM

**Review by KaushikShivam — APPROVED** [review]
# Status: Approved 🎉 

Congratulations, guys!! It's a 👍  for me.
Go ahead and merge it.

All the best for the next project

- Shivam Kaushik

**Comment by dannkkie** [comment]
Thank you

**Pull request merged**
